#!/bin/bash

# change this to run from any directory
cd "$(dirname "$0")"
echo "Running from $(pwd)"

# clear the build directory
# rm -rf build
# mkdir build

#build the project
npx tsc

case $1 in
  build)
    npx tsc
    chmod +x dist/cli.js 
    ;;
  install)
    npm install
    ;;
    *)
    ./dist/cli.js $@
    ;;
esac