#!/bin/bash

# change this to run from any directory
cd "$(dirname "$0")"

case $1 in
  build)
    npx tsc
    chmod +x dist/cli.js 
    ;;
  install)
    npm install
    ;;
  test)
    npm run test
    ;;
  chelp)
    ./dist/cli.js --help
    ;;
  help)
    echo "Usage: ./run.sh [command]"
    echo "Commands:"
    echo "  build: Build the project"
    echo "  install: Install dependencies"
    echo "  URL_FILE: Run the project with the URL file"
    echo "  test: Run the tests"
    echo "  chelp: show the CLI help"
    echo "  help: Show this help"
    ;;
  *)
    ./dist/cli.js $1
    ;;
esac